### ISSUE TITLE
Error while in event 'giveWeaponToPlayer'

### ISSUE THREAD

**Issue by DatMayo** [team-stuyk-alt-v/altV-GunGame#7]
```[22:30:13][Error] [V8] Exception at gungame:file:///C:/Users/ap/Desktop/GunGame/resources/gungame/server/handler/player_main.mjs:93
[22:30:13][Error]                       alt.log(`player.giveWeapon(${matchData.Weapons[player.data.stage].id}, ${matchData.Weapons[player.data.stage].ammo}, true);`);
[22:30:13][Error]   TypeError: Cannot read property 'id' of undefined
    at Player.alt.on (file:///C:/Users/ap/Desktop/GunGame/resources/gungame/server/handler/player_main.mjs:93:70)
    at Timeout.setTimeout [as _onTimeout] (file:///C:/Users/ap/Desktop/GunGame/resources/gungame/server/handler/player_main.mjs:83:25)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

**Comment by DatMayo** [comment]
34b7425264049e4d2f8fc19aa455cb7f0a0038ec
